# Generated by Django 4.0.5 on 2023-07-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_ride_driver_alter_ride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
